### ISSUE TITLE
UI build fails in latest version on master

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#104]
build is broken due to some incompatibility with the ng-meta library. It seems a common issue with many other libraries and angular 2 https://github.com/angular/angular-cli/issues/3707 

```
 ng build --target=production --environment=prod
```

```
ui_1   | ERROR in Error encountered resolving symbol values statically. Calling function 'MetaModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /app/src/app/app.module.ts, resolving symbol AppModule in /app/src/app/app.module.ts
```

```
ERROR in Error encountered resolving symbol values statically. Calling function 'MetaModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /app/src/app/app.module.ts, resolving symbol AppModule in /app/src/app/app.module.ts

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module build failed: BrowserslistError: Unknown version 55 of and_chr
    at error (/app/node_modules/browserslist/index.js:23:15)
    at Function.select (/app/node_modules/browserslist/index.js:452:21)
    at /app/node_modules/browserslist/index.js:109:38
    at Array.forEach (native)
    at browserslist (/app/node_modules/browserslist/index.js:95:16)
    at isSupported (/app/node_modules/caniuse-api/dist/index.js:66:37)
    at /app/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:101:66
    at /app/node_modules/postcss-selector-parser/dist/selectors/container.js:170:26
    at Selector.each (/app/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
    at Selector.walk (/app/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
    at /app/node_modules/postcss-selector-parser/dist/selectors/container.js:173:31
    at Root.each (/app/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
    at Root.walk (/app/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
    at Processor.func (/app/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:80:17)
    at Processor.process (/app/node_modules/postcss-selector-parser/dist/processor.js:34:14)
    at /app/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:121:12
    at Array.every (native)
```

cc/ @prydonius @Angelmmiguel

**Comment by migmartri** [comment]
There is also another error that gets exposed since we added the ng-meta2

```
ui_1   | ERROR in Error encountered resolving symbol values statically. Calling function 'MetaModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /app/src/app/app.module.ts, resolving symbol AppModule in /app/src/app/app.module.ts
```
