### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by migmartri** [helm/monocular#218]
I am experiencing random container restarts with these logs messages

```
time="2017-03-14T12:38:33Z" level=info msg="Processing icon" dest="/root/monocular/repo-data/incubator/kafka/0.1.1/logo-160x160-fit.png" source="/root/monocular/repo-data/incubator/kafka/0.1.1/logo-original.png" 
time="2017-03-14T12:38:33Z" level=info msg="Processing icon" dest="/root/monocular/repo-data/incubator/kafka/0.1.0/logo-160x160-fit.png" source="/root/monocular/repo-data/incubator/kafka/0.1.0/logo-original.png" 
2017/03/14 12:38:37 Serving monocular at http://[::]:8081
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5cef7f]

goroutine 2972 [running]:
panic(0x161ea80, 0xc42000a050)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
net/http.(*persistConn).closeConnIfStillIdle(0xc4218dd200)
        /usr/local/go/src/net/http/transport.go:1311 +0x2f
net/http.(*persistConn).(net/http.closeConnIfStillIdle)-fm()
        /usr/local/go/src/net/http/transport.go:683 +0x2a
created by time.goFunc
        /usr/local/go/src/time/sleep.go:154 +0x44
```

**Comment by migmartri** [comment]
Since the upgrade to 1.7.5, I have not seen the issue. I'll keep an eye on it but will close in the meantime.

https://github.com/helm/monocular/pull/220
